const $ = selector => document.querySelector(selector);
let servers = [], versions = [], activeServer = null, deleteTarget = null, toastTimer;
const showToast = message => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('show'), 3500); };
const setPage = page => { document.querySelectorAll('.page').forEach(el => el.classList.add('hidden')); $(`#${page}-page`).classList.remove('hidden'); document.querySelectorAll('.nav-item').forEach(el => el.classList.toggle('active', el.dataset.page === page)); $('#page-title').textContent = page === 'home' ? 'Your servers' : page === 'servers' ? 'All servers' : 'Server console'; };
function serverCard(server) { const state = server.running ? 'RUNNING' : server.eulaAccepted ? 'READY' : 'NOT INITIALIZED'; return `<article class="server-card" data-folder="${encodeURIComponent(server.folder)}"><span class="server-status ${server.running ? 'running' : ''}">${state}</span><h4>${server.name}</h4><p>MINECRAFT ${server.version} · ${server.ram || 4} GB RAM</p><div class="server-actions"><button class="open-files" data-folder="${encodeURIComponent(server.folder)}">Open files</button><button class="delete-link" data-folder="${encodeURIComponent(server.folder)}">Delete</button></div></article>`; }
function renderServers() { $('#server-count').textContent = servers.length; const markup = servers.length ? servers.map(serverCard).join('') : '<div class="empty">No servers yet. Start with a fresh world.<br><button class="button button-primary" id="empty-new">Make a new server</button></div>'; $('#home-servers').innerHTML = markup; $('#all-servers').innerHTML = markup; document.querySelectorAll('.server-card').forEach(card => card.addEventListener('click', () => openConsole(decodeURIComponent(card.dataset.folder)))); document.querySelectorAll('.open-files').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); window.serverApp.openFolder(decodeURIComponent(button.dataset.folder)); })); document.querySelectorAll('.delete-link').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); openDelete(decodeURIComponent(button.dataset.folder)); })); $('#empty-new')?.addEventListener('click', openModal); }
async function refresh() { try { servers = await window.serverApp.listServers(); renderServers(); } catch (error) { showToast(error.message); } }
async function openModal() { $('#modal').classList.remove('hidden'); $('#modal-error').textContent = ''; if (!versions.length) { try { versions = await window.serverApp.listVersions(); $('#version-select').innerHTML = versions.map(v => `<option value="${v.id}">${v.id}</option>`).join(''); } catch (error) { $('#modal-error').textContent = `Could not load versions: ${error.message}`; } } }
function closeModal() { $('#modal').classList.add('hidden'); }
async function createServer(event) { event.preventDefault(); const submit = event.target.querySelector('button[type=submit]'); const selected = versions.find(v => v.id === $('#version-select').value); submit.disabled = true; submit.textContent = 'Downloading…'; $('#modal-error').textContent = ''; try { await window.serverApp.createServer({ name: $('#server-name').value, version: selected }); closeModal(); event.target.reset(); $('#ram-range').value = 4; $('#ram-output').textContent = '4 GB'; await refresh(); setPage('servers'); showToast('Server created. Open it to initialize.'); } catch (error) { $('#modal-error').textContent = error.message; } finally { submit.disabled = false; submit.textContent = 'Download and create'; } }
function openConsole(folder) { activeServer = servers.find(s => s.folder === folder); if (!activeServer) return; $('#console-name').textContent = activeServer.name; $('#console-version').textContent = `MINECRAFT ${activeServer.version} · ${activeServer.ram || 4} GB RAM`; $('#console-output').textContent = activeServer.eulaAccepted ? 'Server ready. Start it to see live output.\n' : 'This server has not been initialized.\n'; updateStatus(activeServer.running ? 'running' : 'stopped'); setPage('console'); }
function updateStatus(status) { const el = $('#console-status'); el.className = `status-badge ${status}`; el.textContent = status === 'stopped' && activeServer && !activeServer.eulaAccepted ? 'NOT INITIALIZED' : status.toUpperCase(); $('#start-button').textContent = status === 'stopped' && activeServer && !activeServer.eulaAccepted ? 'Initialize server' : 'Start server'; $('#start-button').style.display = status === 'stopped' ? 'block' : 'none'; $('#stop-button').style.display = status === 'stopped' ? 'none' : 'block'; }
async function startActive() { if (!activeServer) return; try { const result = await window.serverApp.startServer({ folder: activeServer.folder, ram: activeServer.ram || 4 }); if (result.needsEula) { $('#eula-modal').classList.remove('hidden'); return; } updateStatus('starting'); $('#console-output').textContent += 'Starting server…\n'; await refresh(); } catch (error) { $('#console-output').textContent += `ERROR: ${error.message}\n`; showToast(error.message); } }
async function acceptEula() { try { await window.serverApp.acceptEula(activeServer.folder); $('#eula-modal').classList.add('hidden'); await refresh(); activeServer = servers.find(s => s.folder === activeServer.folder); updateStatus('stopped'); showToast('EULA accepted. The server is ready to start.'); } catch (error) { showToast(error.message); } }
function openDelete(folder) { deleteTarget = servers.find(s => s.folder === folder); if (!deleteTarget) return; $('#delete-name').value = ''; $('#delete-error').textContent = ''; $('#delete-modal').classList.remove('hidden'); $('#delete-name').focus(); }
async function confirmDelete() { if (!deleteTarget) return; if ($('#delete-name').value !== deleteTarget.name) { $('#delete-error').textContent = 'The name does not match.'; return; } try { await window.serverApp.deleteServer(deleteTarget.folder); $('#delete-modal').classList.add('hidden'); deleteTarget = null; await refresh(); showToast('Server deleted.'); } catch (error) { $('#delete-error').textContent = error.message; } }
$('#hero-new').addEventListener('click', openModal); $('#header-new').addEventListener('click', openModal); $('#page-new').addEventListener('click', openModal); $('#view-all').addEventListener('click', () => setPage('servers')); $('#close-modal').addEventListener('click', closeModal); $('#new-server-form').addEventListener('submit', createServer); $('#ram-range').addEventListener('input', e => $('#ram-output').textContent = `${e.target.value} GB`); document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => setPage(item.dataset.page))); $('#back-servers').addEventListener('click', () => { refresh(); setPage('servers'); }); $('#start-button').addEventListener('click', startActive); $('#clear-console').addEventListener('click', () => $('#console-output').textContent = 'Console cleared.\n'); $('#open-folder').addEventListener('click', () => activeServer && window.serverApp.openFolder(activeServer.folder)); $('#stop-button').addEventListener('click', () => activeServer && window.serverApp.stopServer(activeServer.folder)); $('#command-form').addEventListener('submit', async e => { e.preventDefault(); const input = $('#command-input'); if (!input.value.trim()) return; $('#console-output').textContent += `> ${input.value}\n`; try { await window.serverApp.sendCommand({ folder: activeServer.folder, command: input.value }); } catch (error) { $('#console-output').textContent += `ERROR: ${error.message}\n`; } input.value = ''; }); $('#open-eula').addEventListener('click', () => window.serverApp.openEula()); $('#cancel-eula').addEventListener('click', () => $('#eula-modal').classList.add('hidden')); $('#accept-eula').addEventListener('click', acceptEula); $('#close-delete').addEventListener('click', () => $('#delete-modal').classList.add('hidden')); $('#cancel-delete').addEventListener('click', () => $('#delete-modal').classList.add('hidden')); $('#confirm-delete').addEventListener('click', confirmDelete);
window.serverApp.onServerEvent(event => { if (!activeServer || event.folder !== activeServer.folder) return; if (event.type === 'log') { $('#console-output').textContent += event.data; $('#console-output').scrollTop = $('#console-output').scrollHeight; } if (event.type === 'status') { updateStatus(event.status); refresh(); } if (event.type === 'error') { $('#console-output').textContent += `ERROR: ${event.message}\n`; updateStatus('stopped'); } });
refresh();
