const $ = selector => document.querySelector(selector);
let servers = [], versions = [], activeServer = null, deleteTarget = null, toastTimer;
const showToast = message => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('show'), 3500); };
const setPage = page => { document.querySelectorAll('.page').forEach(el => el.classList.add('hidden')); $(`#${page}-page`).classList.remove('hidden'); document.querySelectorAll('.nav-item').forEach(el => el.classList.toggle('active', el.dataset.page === page)); $('#page-title').textContent = page === 'home' ? 'Your servers' : page === 'servers' ? 'My servers' : page === 'network' ? 'Networking' : page === 'help' ? 'Help' : 'Server console'; if (page === 'network') refreshAgent(); };
function serverCard(server) { const state = server.running ? 'RUNNING' : server.eulaAccepted ? 'READY' : 'NOT INITIALIZED'; return `<article class="server-card" data-folder="${encodeURIComponent(server.folder)}"><span class="server-status ${server.running ? 'running' : ''}">${state}</span><h4>${server.name}</h4><p>MINECRAFT ${server.version} · ${server.ram || 4} GB RAM</p><div class="server-actions"><button class="open-files" data-folder="${encodeURIComponent(server.folder)}">Open files</button><button class="settings-link" data-folder="${encodeURIComponent(server.folder)}">Settings</button><button class="delete-link" data-folder="${encodeURIComponent(server.folder)}">Delete</button></div></article>`; }
function renderServers() { const markup = servers.length ? servers.map(serverCard).join('') : '<div class="empty">No servers yet. Start with a fresh world.<br><button class="button button-primary" id="empty-new">Make a new server</button></div>'; $('#all-servers').innerHTML = markup; document.querySelectorAll('.server-card').forEach(card => card.addEventListener('click', () => openConsole(decodeURIComponent(card.dataset.folder)))); document.querySelectorAll('.open-files').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); window.serverApp.openFolder(decodeURIComponent(button.dataset.folder)); })); document.querySelectorAll('.settings-link').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); openSettings(decodeURIComponent(button.dataset.folder)); })); document.querySelectorAll('.delete-link').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); openDelete(decodeURIComponent(button.dataset.folder)); })); $('#empty-new')?.addEventListener('click', openModal); }
async function refresh() { try { servers = await window.serverApp.listServers(); renderServers(); } catch (error) { showToast(error.message); } }
async function openModal() { $('#modal').classList.remove('hidden'); $('#modal-error').textContent = ''; if (!versions.length) { try { versions = await window.serverApp.listVersions(); $('#version-select').innerHTML = versions.map(v => `<option value="${v.id}">${v.id}</option>`).join(''); } catch (error) { $('#modal-error').textContent = `Could not load versions: ${error.message}`; } } }
function closeModal() { $('#modal').classList.add('hidden'); }
async function createServer(event) { event.preventDefault(); const submit = event.target.querySelector('button[type=submit]'); const selected = versions.find(v => v.id === $('#version-select').value); submit.disabled = true; submit.textContent = 'Downloading…'; $('#modal-error').textContent = ''; try { await window.serverApp.createServer({ name: $('#server-name').value, version: selected }); closeModal(); event.target.reset(); $('#ram-range').value = 4; $('#ram-output').textContent = '4 GB'; await refresh(); setPage('servers'); showToast('Server created. Open it to initialize.'); } catch (error) { $('#modal-error').textContent = error.message; } finally { submit.disabled = false; submit.textContent = 'Download and create'; } }
function openConsole(folder) { activeServer = servers.find(s => s.folder === folder); if (!activeServer) return; $('#console-name').textContent = activeServer.name; $('#console-version').textContent = `MINECRAFT ${activeServer.version} · ${activeServer.ram || 4} GB RAM`; $('#console-output').textContent = activeServer.eulaAccepted ? 'Server ready. Start it to see live output.\n' : 'This server has not been initialized.\n'; updateStatus(activeServer.running ? 'running' : 'stopped'); setPage('console'); }
function updateStatus(status) { const el = $('#console-status'); el.className = `status-badge ${status}`; el.textContent = status === 'stopped' && activeServer && !activeServer.eulaAccepted ? 'NOT INITIALIZED' : status.toUpperCase(); $('#start-button').textContent = status === 'stopped' && activeServer && !activeServer.eulaAccepted ? 'Initialize server' : 'Start server'; $('#start-button').style.display = status === 'stopped' ? 'block' : 'none'; $('#stop-button').style.display = status === 'stopped' ? 'none' : 'block'; }
async function startActive() { if (!activeServer) return; try { const result = await window.serverApp.startServer({ folder: activeServer.folder, ram: activeServer.ram || 4 }); if (result.needsEula) { $('#eula-modal').classList.remove('hidden'); return; } updateStatus('starting'); $('#console-output').textContent += 'Starting server…\n'; await refresh(); } catch (error) { $('#console-output').textContent += `ERROR: ${error.message}\n`; showToast(error.message); } }
async function acceptEula() { try { await window.serverApp.acceptEula(activeServer.folder); $('#eula-modal').classList.add('hidden'); await refresh(); activeServer = servers.find(s => s.folder === activeServer.folder); updateStatus('stopped'); showToast('EULA accepted. The server is ready to start.'); } catch (error) { showToast(error.message); } }
function openDelete(folder) { deleteTarget = servers.find(s => s.folder === folder); if (!deleteTarget) return; $('#delete-target').textContent = deleteTarget.name; $('#delete-name').value = ''; $('#delete-error').textContent = ''; $('#delete-modal').classList.remove('hidden'); $('#delete-name').focus(); }
async function confirmDelete() { if (!deleteTarget) return; if ($('#delete-name').value !== deleteTarget.name) { $('#delete-error').textContent = 'The name does not match.'; return; } try { await window.serverApp.deleteServer(deleteTarget.folder); $('#delete-modal').classList.add('hidden'); deleteTarget = null; await refresh(); showToast('Server deleted.'); } catch (error) { $('#delete-error').textContent = error.message; } }
function openSettings(folder = activeServer?.folder) { const server = servers.find(s => s.folder === folder); if (!server) return; activeServer = server; $('#settings-ram').value = server.ram || 4; $('#settings-ram-output').textContent = `${server.ram || 4} GB`; $('#settings-error').textContent = ''; $('#settings-modal').classList.remove('hidden'); }
async function saveSettings() { if (!activeServer) return; try { const ram = Number($('#settings-ram').value); await window.serverApp.updateServer({ folder: activeServer.folder, ram }); $('#settings-modal').classList.add('hidden'); await refresh(); activeServer = servers.find(s => s.folder === activeServer.folder); $('#console-version').textContent = `MINECRAFT ${activeServer.version} · ${activeServer.ram} GB RAM`; showToast('Memory settings saved.'); } catch (error) { $('#settings-error').textContent = error.message; } }
async function openNetwork() { if (!activeServer) return; $('#network-modal').classList.remove('hidden'); $('#lan-addresses').textContent = 'Checking network addresses…'; try { const info = await window.serverApp.networkInfo(activeServer.folder); $('#local-address').textContent = info.local; $('#lan-addresses').innerHTML = info.lan.length ? info.lan.map(address => `<div class="address-row"><span>${address}</span><button class="text-button copy-address" data-address="${address}">Copy</button></div>`).join('') : 'No LAN address found.'; document.querySelectorAll('.copy-address').forEach(button => button.addEventListener('click', async () => { const address = button.dataset.address || $(`#${button.dataset.target}`).textContent; await navigator.clipboard.writeText(address); showToast('Address copied.'); })); } catch (error) { $('#lan-addresses').textContent = error.message; } }
function setAgentStatus(status) { const el = $('#agent-status'); if (status.running) { el.textContent = 'Connected to playit.gg'; el.className = 'agent-connected'; } else if (status.installed) { el.textContent = 'Installed, not running'; el.className = ''; } else { el.textContent = 'Not installed'; el.className = ''; } $('#install-agent').disabled = status.installed; $('#start-agent').disabled = !status.installed || status.running; $('#stop-agent').disabled = !status.running; }
async function refreshAgent() { try { setAgentStatus(await window.serverApp.playitStatus()); } catch (error) { $('#agent-status').textContent = error.message; } }
async function installAgent() { const button = $('#install-agent'); button.disabled = true; button.textContent = 'Downloading…'; try { setAgentStatus(await window.serverApp.installPlayit()); showToast('playit agent installed.'); } catch (error) { showToast(error.message); } finally { button.textContent = 'Install agent'; refreshAgent(); } }
async function startAgent() { try { await window.serverApp.startPlayit(); setAgentStatus({ installed: true, running: true }); $('#agent-output').textContent += '\nStarting playit agent…\n'; } catch (error) { $('#agent-output').textContent += `\nERROR: ${error.message}\n`; showToast(error.message); } }
async function stopAgent() { await window.serverApp.stopPlayit(); setAgentStatus({ installed: true, running: false }); }
$('#home-new').addEventListener('click', openModal); document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => setPage(item.dataset.page))); $('#close-modal').addEventListener('click', closeModal); $('#new-server-form').addEventListener('submit', createServer); $('#ram-range').addEventListener('input', e => $('#ram-output').textContent = `${e.target.value} GB`); $('#back-servers').addEventListener('click', () => { refresh(); setPage('servers'); }); $('#network-button').addEventListener('click', openNetwork); $('#close-network').addEventListener('click', () => $('#network-modal').classList.add('hidden')); $('#open-playit').addEventListener('click', () => window.serverApp.openPlayit()); $('#open-playit-page').addEventListener('click', () => window.serverApp.openPlayit()); $('#install-agent').addEventListener('click', installAgent); $('#start-agent').addEventListener('click', startAgent); $('#stop-agent').addEventListener('click', stopAgent); $('#settings-button').addEventListener('click', () => openSettings()); $('#close-settings').addEventListener('click', () => $('#settings-modal').classList.add('hidden')); $('#cancel-settings').addEventListener('click', () => $('#settings-modal').classList.add('hidden')); $('#settings-ram').addEventListener('input', e => $('#settings-ram-output').textContent = `${e.target.value} GB`); $('#save-settings').addEventListener('click', saveSettings); $('#start-button').addEventListener('click', startActive); $('#clear-console').addEventListener('click', () => $('#console-output').textContent = 'Console cleared.\n'); $('#open-folder').addEventListener('click', () => activeServer && window.serverApp.openFolder(activeServer.folder)); $('#stop-button').addEventListener('click', () => activeServer && window.serverApp.stopServer(activeServer.folder)); $('#command-form').addEventListener('submit', async e => { e.preventDefault(); const input = $('#command-input'); if (!input.value.trim()) return; $('#console-output').textContent += `> ${input.value}\n`; try { await window.serverApp.sendCommand({ folder: activeServer.folder, command: input.value }); } catch (error) { $('#console-output').textContent += `ERROR: ${error.message}\n`; } input.value = ''; }); $('#open-eula').addEventListener('click', () => window.serverApp.openEula()); $('#cancel-eula').addEventListener('click', () => $('#eula-modal').classList.add('hidden')); $('#accept-eula').addEventListener('click', acceptEula); $('#close-delete').addEventListener('click', () => $('#delete-modal').classList.add('hidden')); $('#cancel-delete').addEventListener('click', () => $('#delete-modal').classList.add('hidden')); $('#confirm-delete').addEventListener('click', confirmDelete);
window.serverApp.onServerEvent(event => { if (!activeServer || event.folder !== activeServer.folder) return; if (event.type === 'log') { $('#console-output').textContent += event.data; $('#console-output').scrollTop = $('#console-output').scrollHeight; } if (event.type === 'status') { updateStatus(event.status); refresh(); } if (event.type === 'error') { $('#console-output').textContent += `ERROR: ${event.message}\n`; updateStatus('stopped'); } });
window.serverApp.onPlayitEvent(event => { if (event.type === 'log') { $('#agent-output').textContent += event.data; $('#agent-output').scrollTop = $('#agent-output').scrollHeight; } if (event.type === 'status') setAgentStatus({ installed: true, running: event.status === 'running' }); if (event.type === 'error') { $('#agent-output').textContent += `ERROR: ${event.message}\n`; setAgentStatus({ installed: true, running: false }); } });
refresh();
